substitutions:
  _REGION: 'us-central1'
  _DOCKER_IMAGE: 'gcr.io/$PROJECT_ID/bikeshare-image'
  _MODEL_NAME: 'bikeshare-model'
  _ENDPOINT_NAME: 'bikeshare-model-endpoint-1'
  _ARTIFACT_URI: 'gs://bikeshare-mlops-kcl/'

steps:
- id: 'Build Docker Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_DOCKER_IMAGE', '.']

- id: 'Push Docker Image To GCR'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_DOCKER_IMAGE']

- id: 'Execute Tests'
  name: '$_DOCKER_IMAGE'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pytest test_training.py

- id: 'Submit Training Job'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'ai'
    - 'custom-jobs'
    - 'create'
    - '--region=$_REGION'
    - '--project=$PROJECT_ID'
    - '--worker-pool-spec=replica-count=1,machine-type=n1-standard-4,container-image-uri=$_DOCKER_IMAGE'
    - '--display-name=bikeshare-model-training'

- id: 'Upload Model'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'ai'
    - 'models'
    - 'upload'
    - '--container-image-uri=us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-0:latest'
    - '--description=$_MODEL_NAME'
    - '--display-name=$_MODEL_NAME'
    - '--artifact-uri=$_ARTIFACT_URI'
    - '--project=$PROJECT_ID'
    - '--region=$_REGION'

- id: 'Fetch Model ID'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud ai models list \
        --region=$_REGION \
        --project=$PROJECT_ID \
        --format="get(MODEL_ID)" \
        --sort-by="createTime" \
        --limit=1 > /workspace/model_id.txt

- id: 'Create Endpoint'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud beta ai endpoints create \
        --display-name=$_ENDPOINT_NAME \
        --format="get(name)" \
        --region=$_REGION \
        --project=$PROJECT_ID > /workspace/endpoint_id.txt

- id: 'Deploy Model Endpoint'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud beta ai endpoints deploy-model $(cat /workspace/endpoint_id.txt) \
        --region=$_REGION \
        --model=$(cat /workspace/model_id.txt) \
        --display-name=bikeshare-model-endpoint \
        --traffic-split=0=100 \
        --machine-type=n1-standard-4
