site_name: side-projects/data2ml-ops
docs_dir: docs
nav:
  - index.md
  - dbt:
    - dbt/dbt-introduction.md
    - dbt/dbt-features.md
    - dbt/dbt-implementation.md
  - Feast:
    - feast/feature-store-introduction.md
    - feast/feast-introduction.md
    - feast/feast-server-deployment.md
    - feast/vertex-ai-feature-store-introduction.md
    - feast/vertex-ai-feature-store-implementation.md
  - MLOps:
    - mlops/mlflow-introduction.md
    - mlops/mlflow-installation.md
    - mlops/mlflow-experiment-with-optuna.md
    - mlops/kserve-installation.md
    - mlops/kserve-model-deployment.md
    - mlops/kserve-introduction.md
    - mlops/mlserver-introduction.md
    - mlops/optuna-introduction.md
  - Others:
    - others/minio-introduction.md
    - others/knative-introduction.md
    - others/istio-introduction.md
    - others/cert-manager-introduction.md
    - others/grpc-introduction.md
    - others/rest-vs-grpc.md

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate 

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - glightbox