site_name: side-projects/data2ml-ops
docs_dir: docs
nav:
  - index.md
  - prerequisites.md
  - dbt:
    - dbt/what-why-when.md
    - dbt/how-it-works.md
    - dbt/in-the-bigger-picture.md
    - dbt/modeling-data.md
  - Feast:
    - feast/what-why-when.md
    - feast/how-it-works.md
    - feast/in-the-bigger-picture.md
    - feast/modeling-features.md
    - feast/deployment.md
  - MinIO:
    - minio/what-why-when.md
    - minio/deployment.md
  - MLflow:
    - mlflow/what-why-when.md
    - mlflow/how-it-works.md
    - mlflow/in-the-bigger-picture.md
    - mlflow/deployment.md
    - mlflow/hpo.ipynb
  - Ray:
    - ray/what-why-when.md
    - ray/how-it-works.md
    - ray/in-the-bigger-picture.md
    - ray/deployment.md
    - ray/ray-tune.md
    - ray/ray-job.md
  - KServe:
    - kserve/what-why-when.md
    - kserve/how-it-works.md
    - kserve/in-the-bigger-picture.md
    - kserve/installation.md
    - kserve/deployment.md
  - Others:
    - others/mlserver-introduction.md
    - others/optuna-introduction.md
    - others/knative-introduction.md
    - others/istio-introduction.md
    - others/cert-manager-introduction.md
    - others/grpc-introduction.md
    - others/rest-vs-grpc.md

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate 

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - glightbox
  - search
  - mkdocs-jupyter # mkdocs-jupyter==0.25.1
  - enumerate-headings:
      toc_depth: 0
      increment_across_pages: false