site_name: DataOps & MLOps
docs_dir: docs
nav:
  - README.md
  - Analytics Engineering:
    - dbt-introduction.md
    - dbt-features.md
    - dbt-implementation.md
    - sqlmesh-introduction.md
    - sqlmesh-implementation.md
  - Feature Store:
    - feature-store-introduction.md
    - vertex-ai-feature-store-introduction.md
    - vertex-ai-feature-store-implementation.md
    - feast-introduction.md
    - feast-server-deployment.md
  - Model Lifecycle Management:
    - minikube-introduction.md
    - mlflow-introduction.md
    - minio-introduction.md
    - mlflow-installation.md
    - optuna-introduction.md
    - mlflow-experiment-with-optuna.md
  - Model Serving:
    - knative-introduction.md
    - istio-introduction.md
    - cert-manager-introduction.md
    - mlserver-introduction.md
    - kserve-introduction.md
    - kserve-installation.md
    - kserve-model-deployment.md
    - grpc-introduction.md
    - rest-vs-grpc.md

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate 

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format