apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-feature-server
  namespace: feast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-feature-server
  template:
    metadata:
      labels:
        app: online-feature-server
    spec:
      containers:
        - name: online-feature-server
          image: feast:v0.1.4
          ports:
            - containerPort: 8080
          env:
            - name: FEAST_FEATURE_SERVER_CONFIG_PATH
              value: /app/config/feature_store.yaml
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: gcp-sa-key
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: gcp-sa-key
          secret:
            secretName: gcp-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: online-feature-server
  namespace: feast
spec:
  selector:
    app: online-feature-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000