apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "fraud-detection-grpc"
spec:
  predictor:
    minReplicas: 0
    scaleTarget: 1
    scaleMetric: qps
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: s3://miflow/2/5ccd7dcabc1f49c1bc45f1f94d945dd6/artifacts/model
      ports:
        - containerPort: 9000
          name: h2c
          protocol: TCP
    serviceAccountName: sa
